name: (EN) Suggest an Enhancement
description: Share an idea or suggestion for improving the server.
title: "[SUGGESTION] Your idea here"
labels: ["enhancement", "user suggestion"]
body:
  - type: markdown
    attributes:
      value: |
        ✨ Thanks for your suggestion! Please describe as clearly as possible.

    id: title
    attributes:
      label: Title of your Idea
      placeholder: e.g., "Make teleportation cost dynamic"
    validations:
      required: true
  - type: textarea
    id: idea
    attributes:
      label: Detailed Description
    validations:
      required: true
  - type: textarea
    id: reason
    attributes:
      label: Why is this a good idea?
    validations:
      required: false